mkdir -p              "${PREFIX}/share/ldraw"
cp -r p               "${PREFIX}/share/ldraw/"
cp -r parts           "${PREFIX}/share/ldraw/"
cp -r models          "${PREFIX}/share/ldraw/"
cp LDConfig.ldr       "${PREFIX}/share/ldraw/"
cp LDCfgalt.ldr       "${PREFIX}/share/ldraw/"
cp LDConfig_TLG.ldr   "${PREFIX}/share/ldraw/"
