{% set parts_version = "2206" %}
{% set mklist_version = "1.6" %}
{% set build_number = "0" %}

package:
  name: ldraw

source:
  - url: http://www.ldraw.org/library/updates/complete.zip
    sha256: a164a0bf1885213ff6c6ae90dd5805097d57ea858ccfae3129792b65f10f5aa9

  - url: http://www.ldraw.org/library/official/LDConfig.ldr
    sha256: 1c41cfed43b935de8b2113d9e9617e786aacadb0b0329cea2842032fdf166905

build:
  number: {{ build_number }}

outputs:
  - name: ldraw-parts
    version: {{ parts_version }}
    script: build_parts.sh   # [unix]
    script: build_parts.bat  # [win]
    test:
      commands:
        - test -d $PREFIX/share/ldraw/parts/           # [unix]
        - test -d $PREFIX/share/ldraw/models/          # [unix]
        - test -f $PREFIX/share/ldraw/models/car.ldr   # [unix]
        - test -f $PREFIX/share/ldraw/parts/u9462.dat  # [unix]
        - if exist %LIBRARY_PREFIX%\share\ldraw\parts\u9462.dat (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\share\ldraw\models\car.ldr (exit 0) else (exit 1)   # [win]

  - name: ldraw-mklist
    version: {{ mklist_version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - unzip      # [not win]
        - m2-unzip   # [win]
        - m2-sed     # [win]
        - make
    script: build_mklist.sh    # [unix]
    script: build_mklist.bat   # [win]
    test:
      commands:
        - test -f $PREFIX/bin/mklist  # [unix]
        - if exist %LIBRARY_PREFIX%\bin\mklist.exe (exit 0) else (exit 1)  # [win]

about:
  home: https://www.ldraw.org/
  license: CC-BY-2.0
  license_family: CC
  license_file: CAlicense.txt
  summary: LDraw parts library
  description: |
    Collection of 3D LEGO parts, 3D part primitives and two example LEGO 3D models
    in LDraw format. This part library is needed by 3D CAD programs such as MLCAD,
    LeoCAD and Konstruktor which allow one to construct LEGO models from
    individual LDraw parts. It is also needed by rendering software such as LDView
    and LdGLite or instruction creation software like LPub4 or Lic.

extra:
  recipe-maintainers:
    - SylvainCorlay
    - wolfv
