travis:
  secure:
    BINSTAR_TOKEN: U4JlqYUXULall9k472xKF1aoIHGVWp2MuQnkYRNf+l1ucEO4nMawjCuT/fCn6kg65HhKt5HdgfWxzo2NxIFhHiZ/rD7Gtd35ZZWNj5oNtiVlrhJi7OS7+s/AdAKBP2/JQArZ7y2o2vxZ8ImS8kp0yOGU4Jq5NK4+B7E6eMM+l/VRloxvj5RzufVZJlLkJB3YmI7EKn4tIhC1qhrN4z8yZvZyvyCEVXfrcW67TSh8eUWTHAu5UUIfT1pQXWJuBTWnQ9rwhr/wGaELF+5m43oRYj+0T5/8eLEkyMS76j7qLCyzSVsLFt0UEBTNT0FAL3JkBOB8NHfTosPOud7jzmAImXs22OLhWDJknm7zaDAaUjhPT3dTBnSQ35eWDak63kwQrn8Q/llTvt2MSa9+SXtXPYczdJtquqSmHt89p4vmUE5tpwc/cusC0hXxom8aVaYAtKpJfMGjTST9iyjqbCPaS+KB+LxzGJqSKuuQBQejRn8cppkLKJm+Z8CxR33sF1p92c8c/oVpqJemF9dVGxeLmcnPdRYEa0MkRNtx+FQa07hTnDeUhqLFmQrtRFWITATBFtFSI26aXsZ7jSuvIg222d6w8/bXPZ7wo4m2TXZIMVras465X8Fi16NxEqbxSgr68wJ5bdS07gRs1guzEu4+Li5wljQY0D4fw66/hhFkRo8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
